---
version: "2.0"

services:
  app:
    image: ubuntu:latest
    
    env:
      - "my_root_password=rncJbegsYD4jdCJE" # root password for ssh connection. пароль root для подключения по ssh
    
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install -y  curl ; curl -s https://raw.githubusercontent.com/Dimokus88/universe/main/script/start.sh | bash ; sleep infinity'   
    
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true 
      - port: 3030
        as: 3030
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 16Gi
        storage:
          size: 150Gi
         
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
